var config = {
  //all this data is generated by firebase. you just copy and paste
    apiKey: "YOUR API KEY",
    authDomain: "YOUR FIREBASE PROJECT DOMAIN",
    databaseURL: "YOUR FIREBASE DATABSE URL",
    projectId: "YOUR PROJECT ID",
    storageBucket: "YOUR FIREBASE STORAGE BUCKET",
    messagingSenderId: "YOUR ID"
};
firebase.initializeApp(config);

var uploadStatus = document.getElementById("uploadStatus");
var fileButton = document.getElementById("fileUpload");

fileButton.addEventListener("change", function(e) {
  var file = e.target.files[0];
  var storageRef = firebase.storage().ref("myfiles/"+file.name);
  var task = storageRef.put(file);

  task.on("state-changed",
    function progress(snapshot){
      var currentProgress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
      uploadStatus.value = currentProgress;
    },
    function error(err) {
      console.log(err);
    },
    function complete() {

    });
});
